Removed ESLint and Prettier (finally)
pulkitvyas08/Karyakram-Frontend pull request #46
Opened 2022-03-29 10:56 UTC by rakshit087

Finally removed Prettier and ESlint. Let me know if further changes are required.

2022-03-29 11:01 UTC, pulkitvyas08 requested changes
More files need to be changed

2022-03-29 11:04 UTC, pulkitvyas08 commented
Please refer to https://github.com/labs-vision/Karyakram-Frontend/pull/32 and note that the following files were changed/added - 
- `.eslintric.json`
- `.prettierrc.json`
- `vite.config.ts`

Make sure to update/delete them as well to take full effect of this PR's target issue. #12

2022-04-03 09:05 UTC, pulkitvyas08 approved these changes

2022-04-03 09:06 UTC, ChiragSaxena5437 approved these changes

2022-04-03 09:09 UTC, merged